export interface PyqTopic {
  id: string;
  name: string;
  count?: number;
}

export interface PyqSubject {
  id: string;
  name: string;
  volume: "Volume 1" | "Volume 2";
  totalCount?: number;
  topics: PyqTopic[];
}

export const PYQ_SUBJECTS: PyqSubject[] = [
  {
    id: "engg-math",
    name: "Engineering Mathematics",
    volume: "Volume 1",
    topics: [
      { id: "em-pyq-1", name: "Calculus - Continuity", count: 9 },
      { id: "em-pyq-2", name: "Calculus - Definite Integral", count: 3 },
      { id: "em-pyq-3", name: "Calculus - Differentiation", count: 10 },
      { id: "em-pyq-4", name: "Calculus - Integration", count: 11 },
      { id: "em-pyq-5", name: "Calculus - Limits", count: 15 },
      { id: "em-pyq-6", name: "Calculus - Maxima Minima", count: 13 },
      { id: "em-pyq-7", name: "Linear Algebra - Determinant", count: 11 },
      { id: "em-pyq-8", name: "Linear Algebra - Eigen Value", count: 33 },
      { id: "em-pyq-9", name: "Linear Algebra - Matrix", count: 22 },
      { id: "em-pyq-10", name: "Linear Algebra - Rank of Matrix", count: 6 },
      { id: "em-pyq-11", name: "Linear Algebra - System of Equations", count: 17 },
      { id: "em-pyq-12", name: "Linear Algebra - Vector Space", count: 6 },
      { id: "em-pyq-13", name: "Probability - Conditional Probability", count: 14 },
      { id: "em-pyq-14", name: "Probability - Expectation", count: 13 },
      { id: "em-pyq-15", name: "Probability - Probability", count: 28 },
      { id: "em-pyq-16", name: "Probability - Random Variable", count: 8 },
      { id: "em-pyq-17", name: "Probability - Uniform Distribution", count: 10 },
      { id: "em-pyq-18", name: "Probability - Variance", count: 1 },
      { id: "em-pyq-extra-calculus-polynomials", name: "Calculus - Polynomials", count: 2 },
      { id: "em-pyq-extra-la-cartesian-coordinates", name: "Linear Algebra - Cartesian Coordinates", count: 1 },
      { id: "em-pyq-extra-la-gaussian-elimination", name: "Linear Algebra - Gaussian Elimination", count: 1 },
      { id: "em-pyq-extra-la-lu-decomposition", name: "Linear Algebra - Lu Decomposition", count: 1 },
      { id: "em-pyq-extra-la-orthonormality", name: "Linear Algebra - Orthonormality", count: 2 },
      { id: "em-pyq-extra-la-svd", name: "Linear Algebra - Singular Value Decomposition", count: 1 },
      { id: "em-pyq-extra-la-subspace", name: "Linear Algebra - Subspace", count: 1 },
      { id: "em-pyq-extra-prob-bayes-theorem", name: "Probability - Bayes Theorem", count: 1 },
      { id: "em-pyq-extra-prob-bayesian-network", name: "Probability - Bayesian Network", count: 2 },
      { id: "em-pyq-extra-prob-bernoulli-distribution", name: "Probability - Bernoulli Distribution", count: 1 },
      { id: "em-pyq-extra-prob-binomial-distribution", name: "Probability - Binomial Distribution", count: 6 },
      { id: "em-pyq-extra-prob-continuous-distribution", name: "Probability - Continuous Distribution", count: 1 },
      { id: "em-pyq-extra-prob-exponential-distribution", name: "Probability - Exponential Distribution", count: 5 },
      { id: "em-pyq-extra-prob-independent-events", name: "Probability - Independent Events", count: 6 },
      { id: "em-pyq-extra-prob-normal-distribution", name: "Probability - Normal Distribution", count: 2 },
      { id: "em-pyq-extra-prob-poisson-distribution", name: "Probability - Poisson Distribution", count: 4 },
      { id: "em-pyq-extra-prob-pdf", name: "Probability - Probability Density Function", count: 1 },
      { id: "em-pyq-extra-prob-pdist", name: "Probability - Probability Distribution", count: 1 },
      { id: "em-pyq-extra-prob-square-invariant", name: "Probability - Square Invariant", count: 1 },
      { id: "em-pyq-extra-prob-statistics", name: "Probability - Statistics", count: 2 },

    ],
  },
  {
    id: "discrete-math",
    name: "Discrete Mathematics",
    volume: "Volume 1",
    topics: [
      { id: "dm-pyq-1", name: "Combinatorics - Balls in Bins", count: 4 },
      { id: "dm-pyq-2", name: "Combinatorics - Counting", count: 4 },
      { id: "dm-pyq-3", name: "Combinatorics - Generating Functions", count: 6 },
      { id: "dm-pyq-4", name: "Combinatorics - Modular Arithmetic", count: 2 },
      { id: "dm-pyq-5", name: "Combinatorics - Pigeonhole Principle", count: 2 },
      { id: "dm-pyq-6", name: "Combinatorics - Recurrence Relation", count: 7 },
      { id: "dm-pyq-7", name: "Graph Theory - Degree of Graph", count: 12 },
      { id: "dm-pyq-8", name: "Graph Theory - Graph Coloring", count: 11 },
      { id: "dm-pyq-9", name: "Graph Theory - Graph Connectivity", count: 40 },
      { id: "dm-pyq-10", name: "Graph Theory - Graph Isomorphism", count: 3 },
      { id: "dm-pyq-11", name: "Graph Theory - Graph Matching", count: 1 },
      { id: "dm-pyq-12", name: "Graph Theory - Graph Planarity", count: 13 },
      { id: "dm-pyq-13", name: "Mathematical Logic - First Order Logic", count: 34 },
      { id: "dm-pyq-14", name: "Mathematical Logic - Propositional Logic", count: 40 },
      { id: "dm-pyq-15", name: "Set Theory & Algebra - Functions", count: 29 },
      { id: "dm-pyq-16", name: "Set Theory & Algebra - Group Theory", count: 33 },
      { id: "dm-pyq-17", name: "Set Theory & Algebra - Lattice", count: 10 },
      { id: "dm-pyq-18", name: "Set Theory & Algebra - Number Theory", count: 7 },
      { id: "dm-pyq-19", name: "Set Theory & Algebra - Partial Order", count: 10 },
      { id: "dm-pyq-20", name: "Set Theory & Algebra - Relations", count: 37 },
      { id: "dm-pyq-21", name: "Set Theory & Algebra - Set Theory", count: 27 },
      { id: "dm-pyq-extra-combinatory", name: "Combinatory - Combinatory", count: 22 },
      { id: "dm-pyq-extra-combinatory-summation", name: "Combinatory - Summation", count: 3 },
      { id: "dm-pyq-extra-graph-counting", name: "Graph Theory - Counting", count: 3 },
      { id: "dm-pyq-extra-logic-logical-reasoning", name: "Mathematical Logic - Logical Reasoning", count: 3 },
      { id: "dm-pyq-extra-set-binary-operation", name: "Set Theory & Algebra - Binary Operation", count: 8 },
      { id: "dm-pyq-extra-set-countable-uncountable", name: "Set Theory & Algebra - Countable Uncountable Set", count: 2 },
      { id: "dm-pyq-extra-set-identify-function", name: "Set Theory & Algebra - Identify Function", count: 1 },
      { id: "dm-pyq-extra-set-induction", name: "Set Theory & Algebra - Mathematical Induction", count: 2 },
      { id: "dm-pyq-extra-set-onto", name: "Set Theory & Algebra - Onto", count: 1 },
      { id: "dm-pyq-extra-set-polynomials", name: "Set Theory & Algebra - Polynomials", count: 4 },

    ],
  },
  {
    id: "dsa",
    name: "Data Structures & Algorithms",
    volume: "Volume 2",
    topics: [
      { id: "dsa-pyq-1", name: "Algorithms - Algorithm Design", count: 8 },
      { id: "dsa-pyq-2", name: "Algorithms - Asymptotic Notation", count: 21 },
      { id: "dsa-pyq-3", name: "Algorithms - Dynamic Programming", count: 9 },
      { id: "dsa-pyq-4", name: "Algorithms - Graph Search", count: 22 },
      { id: "dsa-pyq-5", name: "Algorithms - Greedy Algorithms", count: 5 },
      { id: "dsa-pyq-6", name: "Algorithms - Hashing", count: 7 },
      { id: "dsa-pyq-7", name: "Algorithms - Minimum Spanning Tree", count: 34 },
      { id: "dsa-pyq-8", name: "Algorithms - Quick Sort", count: 14 },
      { id: "dsa-pyq-9", name: "Algorithms - Recurrence Relation", count: 35 },
      { id: "dsa-pyq-10", name: "Algorithms - Searching", count: 7 },
      { id: "dsa-pyq-11", name: "Algorithms - Shortest Path", count: 9 },
      { id: "dsa-pyq-12", name: "Algorithms - Sorting", count: 28 },
      { id: "dsa-pyq-13", name: "Algorithms - Time Complexity", count: 29 },
      { id: "dsa-pyq-14", name: "Data Structures - AVL Tree", count: 6 },
      { id: "dsa-pyq-15", name: "Data Structures - Binary Heap", count: 29 },
      { id: "dsa-pyq-16", name: "Data Structures - Binary Search Tree", count: 36 },
      { id: "dsa-pyq-17", name: "Data Structures - Binary Tree", count: 53 },
      { id: "dsa-pyq-18", name: "Data Structures - Hashing", count: 16 },
      { id: "dsa-pyq-19", name: "Data Structures - Linked List", count: 23 },
      { id: "dsa-pyq-20", name: "Data Structures - Queue", count: 14 },
      { id: "dsa-pyq-21", name: "Data Structures - Stack", count: 18 },
      { id: "dsa-pyq-22", name: "Data Structures - Trees", count: 14 },
      { id: "dsa-pyq-extra-algorithm-design-technique", name: "Algorithms - Algorithm Design Technique", count: 9 },
      { id: "dsa-pyq-extra-asymptotic-notations", name: "Algorithms - Asymptotic Notations", count: 14 },
      { id: "dsa-pyq-extra-bellman-ford", name: "Algorithms - Bellman Ford", count: 2 },
      { id: "dsa-pyq-extra-binary-search", name: "Algorithms - Binary Search", count: 3 },
      { id: "dsa-pyq-extra-bitonic-array", name: "Algorithms - Bitonic Array", count: 1 },
      { id: "dsa-pyq-extra-depth-first-search", name: "Algorithms - Depth First Search", count: 1 },
      { id: "dsa-pyq-extra-dijkstras-algorithm", name: "Algorithms - Dijkstras Algorithm", count: 6 },
      { id: "dsa-pyq-extra-directed-graph", name: "Algorithms - Directed Graph", count: 1 },
      { id: "dsa-pyq-extra-double-hashing", name: "Algorithms - Double Hashing", count: 1 },
      { id: "dsa-pyq-extra-graph-algorithms", name: "Algorithms - Graph Algorithms", count: 11 },
      { id: "dsa-pyq-extra-huffman-code", name: "Algorithms - Huffman Code", count: 6 },
      { id: "dsa-pyq-extra-identity-function", name: "Algorithms - Identify Function", count: 38 },
      { id: "dsa-pyq-extra-insertion-sort", name: "Algorithms - Insertion Sort", count: 3 },
      { id: "dsa-pyq-extra-linear-probing", name: "Algorithms - Linear Probing", count: 1 },
      { id: "dsa-pyq-extra-matrix-chain-ordering", name: "Algorithms - Matrix Chain Ordering", count: 3 },
      { id: "dsa-pyq-extra-merge-sort", name: "Algorithms - Merge Sort", count: 3 },
      { id: "dsa-pyq-extra-merging", name: "Algorithms - Merging", count: 2 },
      { id: "dsa-pyq-extra-prims-algorithm", name: "Algorithms - Prims Algorithm", count: 2 },
      { id: "dsa-pyq-extra-recursion", name: "Algorithms - Recursion", count: 4 },
      { id: "dsa-pyq-extra-space-complexity", name: "Algorithms - Space Complexity", count: 1 },
      { id: "dsa-pyq-extra-strongly-connected-components", name: "Algorithms - Strongly Connected Components", count: 3 },
      { id: "dsa-pyq-extra-topological-sort", name: "Algorithms - Topological Sort", count: 4 },
      { id: "ds-pyq-extra-array", name: "DS - Array", count: 13 },
      { id: "ds-pyq-extra-data-structures", name: "DS - Data Structures", count: 5 },
      { id: "ds-pyq-extra-infix-prefix", name: "DS - Infix Prefix", count: 5 },
      { id: "ds-pyq-extra-number-of-swap", name: "DS - Number of Swap", count: 1 },
      { id: "ds-pyq-extra-time-complexity", name: "DS - Time Complexity", count: 1 },

    ],
  },
  {
    id: "prog",
    name: "Programming in C",
    volume: "Volume 2",
    topics: [
      { id: "prog-pyq-1", name: "Programming in C - Arrays", count: 10 },
      { id: "prog-pyq-2", name: "Programming in C - Identify Function", count: 6 },
      { id: "prog-pyq-3", name: "Programming in C - Loop Invariants", count: 8 },
      { id: "prog-pyq-4", name: "Programming in C - Output", count: 10 },
      { id: "prog-pyq-5", name: "Programming in C - Parameter Passing", count: 12 },
      { id: "prog-pyq-6", name: "Programming in C - Pointers", count: 14 },
      { id: "prog-pyq-7", name: "Programming in C - Programming in C", count: 31 },
      { id: "prog-pyq-8", name: "Programming in C - Recursion", count: 18 },
      { id: "prog-pyq-9", name: "Programming in C - Structures", count: 5 },
      { id: "prog-pyq-10", name: "Programming in C - Switch Case", count: 2 },
      { id: "c-pyq-extra-aliasing", name: "C - Aliasing", count: 1 },
      { id: "c-pyq-extra-goto", name: "C - Goto", count: 2 },
      { id: "c-pyq-extra-programming-constructs", name: "C - Programming Constructs", count: 1 },
      { id: "c-pyq-extra-programming-paradigms", name: "C - Programming Paradigms", count: 2 },
      { id: "c-pyq-extra-strings", name: "C - Strings", count: 1 },
      { id: "c-pyq-extra-type-checking", name: "C - Type Checking", count: 1 },
      { id: "c-pyq-extra-union", name: "C - Union", count: 1 },
      { id: "c-pyq-extra-variable-binding", name: "C - Variable Binding", count: 1 },

    ],
  },
  {
    id: "toc",
    name: "Theory of Computation",
    volume: "Volume 2",
    topics: [
      { id: "toc-pyq-1", name: "TOC - Closure Property", count: 9 },
      { id: "toc-pyq-2", name: "TOC - Context Free Language", count: 33 },
      { id: "toc-pyq-3", name: "TOC - Decidability", count: 29 },
      { id: "toc-pyq-4", name: "TOC - Finite Automata", count: 42 },
      { id: "toc-pyq-5", name: "TOC - Identify Class of Language", count: 31 },
      { id: "toc-pyq-6", name: "TOC - Minimal State Automata", count: 25 },
      { id: "toc-pyq-7", name: "TOC - Pushdown Automata", count: 15 },
      { id: "toc-pyq-8", name: "TOC - Recursively Enumerable Languages", count: 16 },
      { id: "toc-pyq-9", name: "TOC - Regular Expression", count: 29 },
      { id: "toc-pyq-10", name: "TOC - Regular Language", count: 36 },
      { id: "toc-pyq-extra-context-free-grammar", name: "TOC - Context Free Grammar", count: 2 },
      { id: "toc-pyq-extra-countable-uncountable-set", name: "TOC - Countable Uncountable Set", count: 3 },
      { id: "toc-pyq-extra-dpda", name: "TOC - Dpda", count: 1 },
      { id: "toc-pyq-extra-finite-state-machines", name: "TOC - Finite State Machines", count: 1 },
      { id: "toc-pyq-extra-identify-class-language", name: "TOC - Identify Class Language", count: 31 },
      { id: "toc-pyq-extra-non-determinism", name: "TOC - Non Determinism", count: 6 },
      { id: "toc-pyq-extra-number-of-states", name: "TOC - Number of States", count: 1 },
      { id: "toc-pyq-extra-pumping-lemma", name: "TOC - Pumping Lemma", count: 2 },
      { id: "toc-pyq-extra-recursive-languages", name: "TOC - Recursive and Recursively Enumerable Languages", count: 16 },
      { id: "toc-pyq-extra-reduction", name: "TOC - Reduction", count: 2 },
      { id: "toc-pyq-extra-regular-grammar", name: "TOC - Regular Grammar", count: 3 },

    ],
  },
  {
    id: "compiler",
    name: "Compiler Design",
    volume: "Volume 2",
    topics: [
      { id: "compiler-pyq-1", name: "Compiler - Code Optimization", count: 10 },
      { id: "compiler-pyq-2", name: "Compiler - Compilation Phases", count: 12 },
      { id: "compiler-pyq-3", name: "Compiler - First and Follow", count: 6 },
      { id: "compiler-pyq-4", name: "Compiler - Grammar", count: 51 },
      { id: "compiler-pyq-5", name: "Compiler - Intermediate Code", count: 11 },
      { id: "compiler-pyq-6", name: "Compiler - LR Parser", count: 20 },
      { id: "compiler-pyq-7", name: "Compiler - Lexical Analysis", count: 6 },
      { id: "compiler-pyq-8", name: "Compiler - Parameter Passing", count: 14 },
      { id: "compiler-pyq-9", name: "Compiler - Parsing", count: 27 },
      { id: "compiler-pyq-10", name: "Compiler - Runtime Environment", count: 22 },
      { id: "compiler-pyq-11", name: "Compiler - Syntax Directed Translation", count: 17 },
      { id: "compiler-pyq-extra-assembler", name: "Compiler - Assembler", count: 9 },
      { id: "compiler-pyq-extra-backpatching", name: "Compiler - Backpatching", count: 1 },
      { id: "compiler-pyq-extra-basic-blocks", name: "Compiler - Basic Blocks", count: 1 },
      { id: "compiler-pyq-extra-expression-evaluation", name: "Compiler - Expression Evaluation", count: 2 },
      { id: "compiler-pyq-extra-linker", name: "Compiler - Linker", count: 3 },
      { id: "compiler-pyq-extra-live-variable-analysis", name: "Compiler - Live Variable Analysis", count: 3 },
      { id: "compiler-pyq-extra-macros", name: "Compiler - Macros", count: 4 },
      { id: "compiler-pyq-extra-operator-precedence", name: "Compiler - Operator Precedence", count: 3 },
      { id: "compiler-pyq-extra-register-allocation", name: "Compiler - Register Allocation", count: 6 },
      { id: "compiler-pyq-extra-static-single-assignment", name: "Compiler - Static Single Assignment", count: 3 },
      { id: "compiler-pyq-extra-symbol-table", name: "Compiler - Symbol Table", count: 1 },
      { id: "compiler-pyq-extra-variable-scope", name: "Compiler - Variable Scope", count: 2 },

    ],
  },
  {
    id: "os",
    name: "Operating Systems",
    volume: "Volume 2",
    topics: [
      { id: "os-pyq-1", name: "OS - Disk Scheduling", count: 14 },
      { id: "os-pyq-2", name: "OS - File System", count: 9 },
      { id: "os-pyq-3", name: "OS - Interrupts", count: 6 },
      { id: "os-pyq-4", name: "OS - Memory Management", count: 10 },
      { id: "os-pyq-5", name: "OS - Page Replacement", count: 33 },
      { id: "os-pyq-6", name: "OS - Process", count: 5 },
      { id: "os-pyq-7", name: "OS - Process Scheduling", count: 48 },
      { id: "os-pyq-8", name: "OS - Process Synchronization", count: 52 },
      { id: "os-pyq-9", name: "OS - Resource Allocation", count: 27 },
      { id: "os-pyq-10", name: "OS - Semaphore", count: 10 },
      { id: "os-pyq-11", name: "OS - Threads", count: 10 },
      { id: "os-pyq-12", name: "OS - Virtual Memory", count: 43 },
      { id: "os-pyq-extra-context-switch", name: "OS - Context Switch", count: 4 },
      { id: "os-pyq-extra-deadlock-prevention", name: "OS - Deadlock Prevention Avoidance Detection", count: 4 },
      { id: "os-pyq-extra-disk", name: "OS - Disk", count: 31 },
      { id: "os-pyq-extra-fork-system-call", name: "OS - Fork System Call", count: 7 },
      { id: "os-pyq-extra-io-handling", name: "OS - IO Handling", count: 7 },
      { id: "os-pyq-extra-input-output", name: "OS - Input Output", count: 1 },
      { id: "os-pyq-extra-inter-process-communication", name: "OS - Inter Process Communication", count: 1 },
      { id: "os-pyq-extra-linked-allocation", name: "OS - Linked Allocation", count: 1 },
      { id: "os-pyq-extra-multilevel-paging", name: "OS - Multilevel Paging", count: 1 },
      { id: "os-pyq-extra-os-protection", name: "OS - OS Protection", count: 3 },
      { id: "os-pyq-extra-optimal-page-replacement", name: "OS - Optimal Page Replacement", count: 1 },
      { id: "os-pyq-extra-precedence-graph", name: "OS - Precedence Graph", count: 3 },
      { id: "os-pyq-extra-resource-allocation-graph", name: "OS - Resource Allocation Graph", count: 1 },
      { id: "os-pyq-extra-srtf", name: "OS - Srtf", count: 1 },
      { id: "os-pyq-extra-system-calls", name: "OS - System Calls", count: 1 },

    ],
  },
  {
    id: "dbms",
    name: "Database Management Systems",
    volume: "Volume 2",
    topics: [
      { id: "dbms-pyq-1", name: "DBMS - B Tree", count: 31 },
      { id: "dbms-pyq-2", name: "DBMS - Candidate Key", count: 5 },
      { id: "dbms-pyq-3", name: "DBMS - Conflict Serializable", count: 9 },
      { id: "dbms-pyq-4", name: "DBMS - Database Normalization", count: 56 },
      { id: "dbms-pyq-5", name: "DBMS - ER Diagram", count: 12 },
      { id: "dbms-pyq-6", name: "DBMS - Indexing", count: 13 },
      { id: "dbms-pyq-7", name: "DBMS - Joins", count: 7 },
      { id: "dbms-pyq-8", name: "DBMS - Relational Algebra", count: 31 },
      { id: "dbms-pyq-9", name: "DBMS - Relational Calculus", count: 15 },
      { id: "dbms-pyq-10", name: "DBMS - SQL", count: 58 },
      { id: "dbms-pyq-11", name: "DBMS - Transaction and Concurrency", count: 30 },
      { id: "dbms-pyq-extra-database-design", name: "DBMS - Database Design", count: 1 },
      { id: "dbms-pyq-extra-decomposition", name: "DBMS - Decomposition", count: 1 },
      { id: "dbms-pyq-extra-functional-dependency", name: "DBMS - Functional Dependency", count: 2 },
      { id: "dbms-pyq-extra-multivalued-dependency-4nf", name: "DBMS - Multivalued Dependency 4nf", count: 1 },
      { id: "dbms-pyq-extra-natural-join", name: "DBMS - Natural Join", count: 3 },
      { id: "dbms-pyq-extra-query", name: "DBMS - Query", count: 1 },
      { id: "dbms-pyq-extra-referential-integrity", name: "DBMS - Referential Integrity", count: 5 },
      { id: "dbms-pyq-extra-relational-model", name: "DBMS - Relational Model", count: 2 },
      { id: "dbms-pyq-extra-tuple-relational-calculus", name: "DBMS - Tuple Relational Calculus", count: 1 },

    ],
  },
  {
    id: "cn",
    name: "Computer Networks",
    volume: "Volume 2",
    topics: [
      { id: "cn-pyq-1", name: "CN - Application Layer Protocols", count: 12 },
      { id: "cn-pyq-2", name: "CN - Congestion Control", count: 6 },
      { id: "cn-pyq-3", name: "CN - Error Detection", count: 10 },
      { id: "cn-pyq-4", name: "CN - IP Addressing", count: 11 },
      { id: "cn-pyq-5", name: "CN - IP Packet", count: 11 },
      { id: "cn-pyq-6", name: "CN - MAC Protocol", count: 5 },
      { id: "cn-pyq-7", name: "CN - Routing", count: 13 },
      { id: "cn-pyq-8", name: "CN - Sliding Window", count: 15 },
      { id: "cn-pyq-9", name: "CN - Stop and Wait", count: 6 },
      { id: "cn-pyq-10", name: "CN - Subnetting", count: 21 },
      { id: "cn-pyq-11", name: "CN - TCP", count: 22 },
      { id: "cn-pyq-12", name: "CN - UDP", count: 4 },
      { id: "cn-pyq-extra-arp", name: "CN - Arp", count: 1 },
      { id: "cn-pyq-extra-bit-stuffing", name: "CN - Bit Stuffing", count: 2 },
      { id: "cn-pyq-extra-bridges", name: "CN - Bridges", count: 3 },
      { id: "cn-pyq-extra-crc-polynomial", name: "CN - CRC Polynomial", count: 4 },
      { id: "cn-pyq-extra-csma-cd", name: "CN - CSMA CD", count: 6 },
      { id: "cn-pyq-extra-channel-utilization", name: "CN - Channel Utilization", count: 1 },
      { id: "cn-pyq-extra-communication", name: "CN - Communication", count: 4 },
      { id: "cn-pyq-extra-distance-vector-routing", name: "CN - Distance Vector Routing", count: 8 },
      { id: "cn-pyq-extra-ethernet", name: "CN - Ethernet", count: 7 },
      { id: "cn-pyq-extra-fragmentation", name: "CN - Fragmentation", count: 2 },
      { id: "cn-pyq-extra-lan-technologies", name: "CN - LAN Technologies", count: 7 },
      { id: "cn-pyq-extra-network-flow", name: "CN - Network Flow", count: 4 },
      { id: "cn-pyq-extra-network-layering", name: "CN - Network Layering", count: 6 },
      { id: "cn-pyq-extra-network-protocols", name: "CN - Network Protocols", count: 10 },
      { id: "cn-pyq-extra-network-switching", name: "CN - Network Switching", count: 4 },
      { id: "cn-pyq-extra-osi-model", name: "CN - Osi Model", count: 1 },
      { id: "cn-pyq-extra-probability", name: "CN - Probability", count: 1 },
      { id: "cn-pyq-extra-routing-protocols", name: "CN - Routing Protocols", count: 1 },
      { id: "cn-pyq-extra-sockets", name: "CN - Sockets", count: 4 },
      { id: "cn-pyq-extra-token-bucket", name: "CN - Token Bucket", count: 2 },

    ],
  },
  {
    id: "digital-logic",
    name: "Digital Logic",
    volume: "Volume 2",
    topics: [
      { id: "dl-pyq-1", name: "Digital Logic - Adder", count: 9 },
      { id: "dl-pyq-2", name: "Digital Logic - Boolean Algebra", count: 34 },
      { id: "dl-pyq-3", name: "Digital Logic - Circuit Output", count: 40 },
      { id: "dl-pyq-4", name: "Digital Logic - Digital Counter", count: 17 },
      { id: "dl-pyq-5", name: "Digital Logic - Flip Flop", count: 6 },
      { id: "dl-pyq-6", name: "Digital Logic - Floating Point Representation", count: 12 },
      { id: "dl-pyq-7", name: "Digital Logic - K Map", count: 20 },
      { id: "dl-pyq-8", name: "Digital Logic - Min Sum of Products", count: 15 },
      { id: "dl-pyq-9", name: "Digital Logic - Multiplexer", count: 14 },
      { id: "dl-pyq-10", name: "Digital Logic - Number Representation", count: 58 },
      { id: "dl-pyq-11", name: "Digital Logic - Sequential Circuit", count: 1 },
      { id: "dl-pyq-extra-array-multiplier", name: "Digital Logic - Array Multiplier", count: 2 },
      { id: "dl-pyq-extra-booths-algorithm", name: "Digital Logic - Booths Algorithm", count: 7 },
      { id: "dl-pyq-extra-canonical-normal-form", name: "Digital Logic - Canonical Normal Form", count: 9 },
      { id: "dl-pyq-extra-carry-generator", name: "Digital Logic - Carry Generator", count: 2 },
      { id: "dl-pyq-extra-combinational-circuit", name: "Digital Logic - Combinational Circuit", count: 2 },
      { id: "dl-pyq-extra-decoder", name: "Digital Logic - Decoder", count: 3 },
      { id: "dl-pyq-extra-digital-circuits", name: "Digital Logic - Digital Circuits", count: 6 },
      { id: "dl-pyq-extra-finite-state-machines", name: "Digital Logic - Finite State Machines", count: 4 },
      { id: "dl-pyq-extra-fixed-point-representation", name: "Digital Logic - Fixed Point Representation", count: 2 },
      { id: "dl-pyq-extra-functional-completeness", name: "Digital Logic - Functional Completeness", count: 7 },
      { id: "dl-pyq-extra-ieee-representation", name: "Digital Logic - IEEE Representation", count: 8 },
      { id: "dl-pyq-extra-memory-interfacing", name: "Digital Logic - Memory Interfacing", count: 5 },
      { id: "dl-pyq-extra-min-no-gates", name: "Digital Logic - Min No Gates", count: 4 },
      { id: "dl-pyq-extra-min-products-of-sum-form", name: "Digital Logic - Min Products of Sum Form", count: 2 },
      { id: "dl-pyq-extra-prime-implicants", name: "Digital Logic - Prime Implicants", count: 2 },
      { id: "dl-pyq-extra-rom", name: "Digital Logic - ROM", count: 4 },
      { id: "dl-pyq-extra-ripple-counter-operation", name: "Digital Logic - Ripple Counter Operation", count: 1 },
      { id: "dl-pyq-extra-shift-registers", name: "Digital Logic - Shift Registers", count: 2 },
      { id: "dl-pyq-extra-static-hazard", name: "Digital Logic - Static Hazard", count: 1 },
      { id: "dl-pyq-extra-synchronous-asynchronous-circuits", name: "Digital Logic - Synchronous Asynchronous Circuits", count: 4 },

    ],
  },
  {
    id: "coa",
    name: "Computer Organization & Architecture",
    volume: "Volume 2",
    topics: [
      { id: "coa-pyq-1", name: "COA - Addressing Modes", count: 18 },
      { id: "coa-pyq-2", name: "COA - Cache Memory", count: 73 },
      { id: "coa-pyq-3", name: "COA - DMA", count: 9 },
      { id: "coa-pyq-4", name: "COA - Data Path", count: 7 },
      { id: "coa-pyq-5", name: "COA - Instruction Format", count: 9 },
      { id: "coa-pyq-6", name: "COA - Interrupts", count: 9 },
      { id: "coa-pyq-7", name: "COA - Machine Instruction", count: 21 },
      { id: "coa-pyq-8", name: "COA - Memory Interfacing", count: 6 },
      { id: "coa-pyq-9", name: "COA - Microprogramming", count: 13 },
      { id: "coa-pyq-10", name: "COA - Pipelining", count: 43 },
      { id: "coa-pyq-11", name: "COA - Runtime Environment", count: 2 },
      { id: "coa-pyq-12", name: "COA - Virtual Memory", count: 3 },
      { id: "coa-pyq-extra-average-memory-access-time", name: "COA - Average Memory Access Time", count: 2 },
      { id: "coa-pyq-extra-cisc-risc-architecture", name: "COA - CISC RISC Architecture", count: 2 },
      { id: "coa-pyq-extra-clock-cycles", name: "COA - Clock Cycles", count: 1 },
      { id: "coa-pyq-extra-data-dependency", name: "COA - Data Dependency", count: 2 },
      { id: "coa-pyq-extra-io-handling", name: "COA - IO Handling", count: 7 },
      { id: "coa-pyq-extra-instruction-execution", name: "COA - Instruction Execution", count: 6 },
      { id: "coa-pyq-extra-instruction-set-architecture", name: "COA - Instruction Set Architecture", count: 1 },
      { id: "coa-pyq-extra-speedup", name: "COA - Speedup", count: 4 },

    ],
  },
  {
    id: "aptitude",
    name: "General Aptitude",
    volume: "Volume 1",
    topics: [
      { id: "apt-pyq-1", name: "Analytical Aptitude - Direction Sense", count: 12 },
      { id: "apt-pyq-2", name: "Analytical Aptitude - Logical Reasoning", count: 39 },
      { id: "apt-pyq-3", name: "Analytical Aptitude - Seating Arrangement", count: 4 },
      { id: "apt-pyq-4", name: "Analytical Aptitude - Sequence Series", count: 12 },
      { id: "apt-pyq-5", name: "Analytical Aptitude - Statements Follow", count: 33 },
      { id: "apt-pyq-6", name: "Quantitative Aptitude - Data Interpretation", count: 5 },
      { id: "apt-pyq-7", name: "Quantitative Aptitude - Geometry", count: 29 },
      { id: "apt-pyq-8", name: "Quantitative Aptitude - Logarithms", count: 14 },
      { id: "apt-pyq-9", name: "Quantitative Aptitude - Percentage", count: 21 },
      { id: "apt-pyq-10", name: "Quantitative Aptitude - Probability", count: 29 },
      { id: "apt-pyq-11", name: "Quantitative Aptitude - Ratio Proportion", count: 26 },
      { id: "apt-pyq-12", name: "Quantitative Aptitude - Speed Time Distance", count: 19 },
      { id: "apt-pyq-13", name: "Quantitative Aptitude - Venn Diagram", count: 16 },
      { id: "apt-pyq-14", name: "Spatial Aptitude - Image Rotation", count: 7 },
      { id: "apt-pyq-15", name: "Spatial Aptitude - Paper Folding", count: 12 },
      { id: "apt-pyq-16", name: "Verbal Aptitude - Most Appropriate Word", count: 113 },
      { id: "apt-pyq-17", name: "Verbal Aptitude - Passage Reading", count: 57 },
      { id: "apt-pyq-18", name: "Verbal Aptitude - Synonyms", count: 19 },
      { id: "apt-pyq-19", name: "Verbal Aptitude - Tenses", count: 25 },
      { id: "apt-pyq-20", name: "Verbal Aptitude - Word Pairs", count: 30 },
      { id: "ga-pyq-extra-age-relation", name: "Analytical Aptitude - Age Relation", count: 2 },
      { id: "ga-pyq-extra-code-words", name: "Analytical Aptitude - Code Words", count: 5 },
      { id: "ga-pyq-extra-coding-decoding", name: "Analytical Aptitude - Coding Decoding", count: 1 },
      { id: "ga-pyq-extra-counting-figure", name: "Analytical Aptitude - Counting Figure", count: 1 },
      { id: "ga-pyq-extra-family-relationship", name: "Analytical Aptitude - Family Relationship", count: 7 },
      { id: "ga-pyq-extra-inequality", name: "Analytical Aptitude - Inequality", count: 1 },
      { id: "ga-pyq-extra-logical-inference", name: "Analytical Aptitude - Logical Inference", count: 1 },
      { id: "ga-pyq-extra-number-relations", name: "Analytical Aptitude - Number Relations", count: 3 },
      { id: "ga-pyq-extra-odd-one", name: "Analytical Aptitude - Odd One", count: 6 },
      { id: "ga-pyq-extra-passage-reading", name: "Analytical Aptitude - Passage Reading", count: 6 },
      { id: "ga-pyq-extra-round-table", name: "Analytical Aptitude - Round Table Arrangement", count: 6 },
      { id: "ga-pyq-extra-absolute-value", name: "Quantitative Aptitude - Absolute Value", count: 7 },
      { id: "ga-pyq-extra-age-relation-q", name: "Quantitative Aptitude - Age Relation", count: 1 },
      { id: "ga-pyq-extra-algebra", name: "Quantitative Aptitude - Algebra", count: 6 },
      { id: "ga-pyq-extra-alligation-mixture", name: "Quantitative Aptitude - Alligation Mixture", count: 3 },
      { id: "ga-pyq-extra-area", name: "Quantitative Aptitude - Area", count: 2 },
      { id: "ga-pyq-extra-arithmetic-series", name: "Quantitative Aptitude - Arithmetic Series", count: 9 },
      { id: "ga-pyq-extra-average", name: "Quantitative Aptitude - Average", count: 3 },
      { id: "ga-pyq-extra-bar-graph", name: "Quantitative Aptitude - Bar Graph", count: 18 },
      { id: "ga-pyq-extra-calendar", name: "Quantitative Aptitude - Calendar", count: 2 },
      { id: "ga-pyq-extra-cartesian-coordinates", name: "Quantitative Aptitude - Cartesian Coordinates", count: 10 },
      { id: "ga-pyq-extra-circle", name: "Quantitative Aptitude - Circle", count: 7 },
      { id: "ga-pyq-extra-clock-time", name: "Quantitative Aptitude - Clock Time", count: 10 },
      { id: "ga-pyq-extra-combinatory", name: "Quantitative Aptitude - Combinatory", count: 12 },
      { id: "ga-pyq-extra-compound-interest", name: "Quantitative Aptitude - Compound Interest", count: 5 },
      { id: "ga-pyq-extra-conditional-probability", name: "Quantitative Aptitude - Conditional Probability", count: 6 },
      { id: "ga-pyq-extra-cones", name: "Quantitative Aptitude - Cones", count: 1 },
      { id: "ga-pyq-extra-contour-plots", name: "Quantitative Aptitude - Contour Plots", count: 4 },
      { id: "ga-pyq-extra-cost-market-price", name: "Quantitative Aptitude - Cost Market Price", count: 6 },
      { id: "ga-pyq-extra-counting", name: "Quantitative Aptitude - Counting", count: 6 },
      { id: "ga-pyq-extra-cube", name: "Quantitative Aptitude - Cube", count: 2 },
      { id: "ga-pyq-extra-currency-notes", name: "Quantitative Aptitude - Currency Notes", count: 1 },
      { id: "ga-pyq-extra-curves", name: "Quantitative Aptitude - Curves", count: 2 },
      { id: "ga-pyq-extra-dip", name: "Quantitative Aptitude - Digital Image Processing", count: 1 },
      { id: "ga-pyq-extra-factors", name: "Quantitative Aptitude - Factors", count: 4 },
      { id: "ga-pyq-extra-fractions", name: "Quantitative Aptitude - Fractions", count: 4 },
      { id: "ga-pyq-extra-functions", name: "Quantitative Aptitude - Functions", count: 18 },
      { id: "ga-pyq-extra-graph-coloring", name: "Quantitative Aptitude - Graph Coloring", count: 1 },
      { id: "ga-pyq-extra-inequality-q", name: "Quantitative Aptitude - Inequality", count: 4 },
      { id: "ga-pyq-extra-lcm-hcf", name: "Quantitative Aptitude - LCM HCF", count: 1 },
      { id: "ga-pyq-extra-line-graph", name: "Quantitative Aptitude - Line Graph", count: 12 },
      { id: "ga-pyq-extra-lines", name: "Quantitative Aptitude - Lines", count: 1 },
      { id: "ga-pyq-extra-maps", name: "Quantitative Aptitude - Maps", count: 1 },
      { id: "ga-pyq-extra-maxima-minima", name: "Quantitative Aptitude - Maxima Minima", count: 4 },
      { id: "ga-pyq-extra-mensuration", name: "Quantitative Aptitude - Mensuration", count: 1 },
      { id: "ga-pyq-extra-modular-arithmetic", name: "Quantitative Aptitude - Modular Arithmetic", count: 2 },
      { id: "ga-pyq-extra-number-series", name: "Quantitative Aptitude - Number Series", count: 10 },
      { id: "ga-pyq-extra-number-system", name: "Quantitative Aptitude - Number System", count: 7 },
      { id: "ga-pyq-extra-number-theory", name: "Quantitative Aptitude - Number Theory", count: 6 },
      { id: "ga-pyq-extra-numerical-computation", name: "Quantitative Aptitude - Numerical Computation", count: 14 },
      { id: "ga-pyq-extra-percentage", name: "Quantitative Aptitude - Percentage", count: 21 },
      { id: "ga-pyq-extra-permutation-combination", name: "Quantitative Aptitude - Permutation and Combination", count: 4 },
      { id: "ga-pyq-extra-pie-chart", name: "Quantitative Aptitude - Pie Chart", count: 16 },
      { id: "ga-pyq-extra-polynomials", name: "Quantitative Aptitude - Polynomials", count: 4 },
      { id: "ga-pyq-extra-powers", name: "Quantitative Aptitude - Powers", count: 1 },
      { id: "ga-pyq-extra-prime-numbers", name: "Quantitative Aptitude - Prime Numbers", count: 1 },
      { id: "ga-pyq-extra-probability-pdf", name: "Quantitative Aptitude - Probability Density Function", count: 1 },
      { id: "ga-pyq-extra-profit-loss", name: "Quantitative Aptitude - Profit Loss", count: 6 },
      { id: "ga-pyq-extra-quadratic-equations", name: "Quantitative Aptitude - Quadratic Equations", count: 11 },
      { id: "ga-pyq-extra-radar-chart", name: "Quantitative Aptitude - Radar Chart", count: 1 },
      { id: "ga-pyq-extra-ratio-proportion", name: "Quantitative Aptitude - Ratio Proportion", count: 26 },
      { id: "ga-pyq-extra-scatter-plot", name: "Quantitative Aptitude - Scatter Plot", count: 1 },
      { id: "ga-pyq-extra-set-theory", name: "Quantitative Aptitude - Set Theory", count: 1 },
      { id: "ga-pyq-extra-squares", name: "Quantitative Aptitude - Squares", count: 4 },
      { id: "ga-pyq-extra-statistics", name: "Quantitative Aptitude - Statistics", count: 9 },
      { id: "ga-pyq-extra-system-equations", name: "Quantitative Aptitude - System of Equations", count: 1 },
      { id: "ga-pyq-extra-tables", name: "Quantitative Aptitude - Tables", count: 1 },
      { id: "ga-pyq-extra-tabular-data", name: "Quantitative Aptitude - Tabular Data", count: 10 },
      { id: "ga-pyq-extra-triangles", name: "Quantitative Aptitude - Triangles", count: 11 },
      { id: "ga-pyq-extra-trigonometry", name: "Quantitative Aptitude - Trigonometry", count: 1 },
      { id: "ga-pyq-extra-unit-digit", name: "Quantitative Aptitude - Unit Digit", count: 2 },
      { id: "ga-pyq-extra-volume", name: "Quantitative Aptitude - Volume", count: 2 },
      { id: "ga-pyq-extra-work-time", name: "Quantitative Aptitude - Work Time", count: 17 },
      { id: "ga-pyq-extra-assembling-pieces", name: "Spatial Aptitude - Assembling Pieces", count: 4 },
      { id: "ga-pyq-extra-grouping", name: "Spatial Aptitude - Grouping", count: 1 },
      { id: "ga-pyq-extra-mirror-image", name: "Spatial Aptitude - Mirror Image", count: 7 },
      { id: "ga-pyq-extra-patterns-3d", name: "Spatial Aptitude - Patterns In Three Dimensions", count: 8 },
      { id: "ga-pyq-extra-patterns-2d", name: "Spatial Aptitude - Patterns In Two Dimensions", count: 9 },
      { id: "ga-pyq-extra-articles", name: "Verbal Aptitude - Articles", count: 2 },
      { id: "ga-pyq-extra-comparative-forms", name: "Verbal Aptitude - Comparative Forms", count: 7 },
      { id: "ga-pyq-extra-english-grammar", name: "Verbal Aptitude - English Grammar", count: 12 },
      { id: "ga-pyq-extra-grammatical-error", name: "Verbal Aptitude - Grammatical Error", count: 9 },
      { id: "ga-pyq-extra-incorrect-sentence-part", name: "Verbal Aptitude - Incorrect Sentence Part", count: 5 },
      { id: "ga-pyq-extra-narrative-sequencing", name: "Verbal Aptitude - Narrative Sequencing", count: 1 },
      { id: "ga-pyq-extra-noun-verb-adjective", name: "Verbal Aptitude - Noun Verb Adjective", count: 3 },
      { id: "ga-pyq-extra-opposite", name: "Verbal Aptitude - Opposite", count: 5 },
      { id: "ga-pyq-extra-phrasal-verb", name: "Verbal Aptitude - Phrasal Verb", count: 2 },
      { id: "ga-pyq-extra-phrase-meaning", name: "Verbal Aptitude - Phrase Meaning", count: 8 },
      { id: "ga-pyq-extra-prepositions", name: "Verbal Aptitude - Prepositions", count: 8 },
      { id: "ga-pyq-extra-pronouns", name: "Verbal Aptitude - Pronouns", count: 4 },
      { id: "ga-pyq-extra-sentence-ordering", name: "Verbal Aptitude - Sentence Ordering", count: 5 },
      { id: "ga-pyq-extra-statement-sufficiency", name: "Verbal Aptitude - Statement Sufficiency", count: 2 },
      { id: "ga-pyq-extra-synonyms", name: "Verbal Aptitude - Synonyms", count: 19 },
      { id: "ga-pyq-extra-verbal-reasoning", name: "Verbal Aptitude - Verbal Reasoning", count: 40 },
      { id: "ga-pyq-extra-word-meaning", name: "Verbal Aptitude - Word Meaning", count: 17 },

    ],
  },
];

export function getPyqSubjectById(subjectId: string): PyqSubject | undefined {
  return PYQ_SUBJECTS.find((subject) => subject.id === subjectId);
}
