export interface PyqTopic {
  id: string;
  name: string;
  count?: number;
}

export interface PyqSubject {
  id: string;
  name: string;
  volume: "Volume 1" | "Volume 2";
  totalCount?: number;
  topics: PyqTopic[];
}

export const PYQ_SUBJECTS: PyqSubject[] = [
  {
    id: "engg-math",
    name: "Engineering Mathematics",
    volume: "Volume 1",
    topics: [
      { id: "em-pyq-1", name: "Calculus - Continuity", count: 9 },
      { id: "em-pyq-2", name: "Calculus - Definite Integral", count: 3 },
      { id: "em-pyq-3", name: "Calculus - Differentiation", count: 10 },
      { id: "em-pyq-4", name: "Calculus - Integration", count: 11 },
      { id: "em-pyq-5", name: "Calculus - Limits", count: 15 },
      { id: "em-pyq-6", name: "Calculus - Maxima Minima", count: 13 },
      { id: "em-pyq-7", name: "Linear Algebra - Determinant", count: 11 },
      { id: "em-pyq-8", name: "Linear Algebra - Eigen Value", count: 33 },
      { id: "em-pyq-9", name: "Linear Algebra - Matrix", count: 22 },
      { id: "em-pyq-10", name: "Linear Algebra - Rank of Matrix", count: 6 },
      { id: "em-pyq-11", name: "Linear Algebra - System of Equations", count: 17 },
      { id: "em-pyq-12", name: "Linear Algebra - Vector Space", count: 6 },
      { id: "em-pyq-13", name: "Probability - Conditional Probability", count: 14 },
      { id: "em-pyq-14", name: "Probability - Expectation", count: 13 },
      { id: "em-pyq-15", name: "Probability - Probability", count: 28 },
      { id: "em-pyq-16", name: "Probability - Random Variable", count: 8 },
      { id: "em-pyq-17", name: "Probability - Uniform Distribution", count: 10 },
      { id: "em-pyq-18", name: "Probability - Variance", count: 1 },
    ],
  },
  {
    id: "discrete-math",
    name: "Discrete Mathematics",
    volume: "Volume 1",
    topics: [
      { id: "dm-pyq-1", name: "Combinatorics - Balls in Bins", count: 4 },
      { id: "dm-pyq-2", name: "Combinatorics - Counting", count: 4 },
      { id: "dm-pyq-3", name: "Combinatorics - Generating Functions", count: 6 },
      { id: "dm-pyq-4", name: "Combinatorics - Modular Arithmetic", count: 2 },
      { id: "dm-pyq-5", name: "Combinatorics - Pigeonhole Principle", count: 2 },
      { id: "dm-pyq-6", name: "Combinatorics - Recurrence Relation", count: 7 },
      { id: "dm-pyq-7", name: "Graph Theory - Degree of Graph", count: 12 },
      { id: "dm-pyq-8", name: "Graph Theory - Graph Coloring", count: 11 },
      { id: "dm-pyq-9", name: "Graph Theory - Graph Connectivity", count: 40 },
      { id: "dm-pyq-10", name: "Graph Theory - Graph Isomorphism", count: 3 },
      { id: "dm-pyq-11", name: "Graph Theory - Graph Matching", count: 1 },
      { id: "dm-pyq-12", name: "Graph Theory - Graph Planarity", count: 13 },
      { id: "dm-pyq-13", name: "Mathematical Logic - First Order Logic", count: 34 },
      { id: "dm-pyq-14", name: "Mathematical Logic - Propositional Logic", count: 40 },
      { id: "dm-pyq-15", name: "Set Theory & Algebra - Functions", count: 29 },
      { id: "dm-pyq-16", name: "Set Theory & Algebra - Group Theory", count: 33 },
      { id: "dm-pyq-17", name: "Set Theory & Algebra - Lattice", count: 10 },
      { id: "dm-pyq-18", name: "Set Theory & Algebra - Number Theory", count: 7 },
      { id: "dm-pyq-19", name: "Set Theory & Algebra - Partial Order", count: 10 },
      { id: "dm-pyq-20", name: "Set Theory & Algebra - Relations", count: 37 },
      { id: "dm-pyq-21", name: "Set Theory & Algebra - Set Theory", count: 27 },
    ],
  },
  {
    id: "dsa",
    name: "Data Structures & Algorithms",
    volume: "Volume 2",
    topics: [
      { id: "dsa-pyq-1", name: "Algorithms - Algorithm Design", count: 8 },
      { id: "dsa-pyq-2", name: "Algorithms - Asymptotic Notation", count: 21 },
      { id: "dsa-pyq-3", name: "Algorithms - Dynamic Programming", count: 9 },
      { id: "dsa-pyq-4", name: "Algorithms - Graph Search", count: 22 },
      { id: "dsa-pyq-5", name: "Algorithms - Greedy Algorithms", count: 5 },
      { id: "dsa-pyq-6", name: "Algorithms - Hashing", count: 7 },
      { id: "dsa-pyq-7", name: "Algorithms - Minimum Spanning Tree", count: 34 },
      { id: "dsa-pyq-8", name: "Algorithms - Quick Sort", count: 14 },
      { id: "dsa-pyq-9", name: "Algorithms - Recurrence Relation", count: 35 },
      { id: "dsa-pyq-10", name: "Algorithms - Searching", count: 7 },
      { id: "dsa-pyq-11", name: "Algorithms - Shortest Path", count: 9 },
      { id: "dsa-pyq-12", name: "Algorithms - Sorting", count: 28 },
      { id: "dsa-pyq-13", name: "Algorithms - Time Complexity", count: 29 },
      { id: "dsa-pyq-14", name: "Data Structures - AVL Tree", count: 6 },
      { id: "dsa-pyq-15", name: "Data Structures - Binary Heap", count: 29 },
      { id: "dsa-pyq-16", name: "Data Structures - Binary Search Tree", count: 36 },
      { id: "dsa-pyq-17", name: "Data Structures - Binary Tree", count: 53 },
      { id: "dsa-pyq-18", name: "Data Structures - Hashing", count: 16 },
      { id: "dsa-pyq-19", name: "Data Structures - Linked List", count: 23 },
      { id: "dsa-pyq-20", name: "Data Structures - Queue", count: 14 },
      { id: "dsa-pyq-21", name: "Data Structures - Stack", count: 18 },
      { id: "dsa-pyq-22", name: "Data Structures - Trees", count: 14 },
    ],
  },
  {
    id: "prog",
    name: "Programming in C",
    volume: "Volume 2",
    topics: [
      { id: "prog-pyq-1", name: "Programming in C - Arrays", count: 10 },
      { id: "prog-pyq-2", name: "Programming in C - Identify Function", count: 6 },
      { id: "prog-pyq-3", name: "Programming in C - Loop Invariants", count: 8 },
      { id: "prog-pyq-4", name: "Programming in C - Output", count: 10 },
      { id: "prog-pyq-5", name: "Programming in C - Parameter Passing", count: 12 },
      { id: "prog-pyq-6", name: "Programming in C - Pointers", count: 14 },
      { id: "prog-pyq-7", name: "Programming in C - Programming in C", count: 31 },
      { id: "prog-pyq-8", name: "Programming in C - Recursion", count: 18 },
      { id: "prog-pyq-9", name: "Programming in C - Structures", count: 5 },
      { id: "prog-pyq-10", name: "Programming in C - Switch Case", count: 2 },
    ],
  },
  {
    id: "toc",
    name: "Theory of Computation",
    volume: "Volume 2",
    topics: [
      { id: "toc-pyq-1", name: "TOC - Closure Property", count: 9 },
      { id: "toc-pyq-2", name: "TOC - Context Free Language", count: 33 },
      { id: "toc-pyq-3", name: "TOC - Decidability", count: 29 },
      { id: "toc-pyq-4", name: "TOC - Finite Automata", count: 42 },
      { id: "toc-pyq-5", name: "TOC - Identify Class of Language", count: 31 },
      { id: "toc-pyq-6", name: "TOC - Minimal State Automata", count: 25 },
      { id: "toc-pyq-7", name: "TOC - Pushdown Automata", count: 15 },
      { id: "toc-pyq-8", name: "TOC - Recursively Enumerable Languages", count: 16 },
      { id: "toc-pyq-9", name: "TOC - Regular Expression", count: 29 },
      { id: "toc-pyq-10", name: "TOC - Regular Language", count: 36 },
    ],
  },
  {
    id: "compiler",
    name: "Compiler Design",
    volume: "Volume 2",
    topics: [
      { id: "compiler-pyq-1", name: "Compiler - Code Optimization", count: 10 },
      { id: "compiler-pyq-2", name: "Compiler - Compilation Phases", count: 12 },
      { id: "compiler-pyq-3", name: "Compiler - First and Follow", count: 6 },
      { id: "compiler-pyq-4", name: "Compiler - Grammar", count: 51 },
      { id: "compiler-pyq-5", name: "Compiler - Intermediate Code", count: 11 },
      { id: "compiler-pyq-6", name: "Compiler - LR Parser", count: 20 },
      { id: "compiler-pyq-7", name: "Compiler - Lexical Analysis", count: 6 },
      { id: "compiler-pyq-8", name: "Compiler - Parameter Passing", count: 14 },
      { id: "compiler-pyq-9", name: "Compiler - Parsing", count: 27 },
      { id: "compiler-pyq-10", name: "Compiler - Runtime Environment", count: 22 },
      { id: "compiler-pyq-11", name: "Compiler - Syntax Directed Translation", count: 17 },
    ],
  },
  {
    id: "os",
    name: "Operating Systems",
    volume: "Volume 2",
    topics: [
      { id: "os-pyq-1", name: "OS - Disk Scheduling", count: 14 },
      { id: "os-pyq-2", name: "OS - File System", count: 9 },
      { id: "os-pyq-3", name: "OS - Interrupts", count: 6 },
      { id: "os-pyq-4", name: "OS - Memory Management", count: 10 },
      { id: "os-pyq-5", name: "OS - Page Replacement", count: 33 },
      { id: "os-pyq-6", name: "OS - Process", count: 5 },
      { id: "os-pyq-7", name: "OS - Process Scheduling", count: 48 },
      { id: "os-pyq-8", name: "OS - Process Synchronization", count: 52 },
      { id: "os-pyq-9", name: "OS - Resource Allocation", count: 27 },
      { id: "os-pyq-10", name: "OS - Semaphore", count: 10 },
      { id: "os-pyq-11", name: "OS - Threads", count: 10 },
      { id: "os-pyq-12", name: "OS - Virtual Memory", count: 43 },
    ],
  },
  {
    id: "dbms",
    name: "Database Management Systems",
    volume: "Volume 2",
    topics: [
      { id: "dbms-pyq-1", name: "DBMS - B Tree", count: 31 },
      { id: "dbms-pyq-2", name: "DBMS - Candidate Key", count: 5 },
      { id: "dbms-pyq-3", name: "DBMS - Conflict Serializable", count: 9 },
      { id: "dbms-pyq-4", name: "DBMS - Database Normalization", count: 56 },
      { id: "dbms-pyq-5", name: "DBMS - ER Diagram", count: 12 },
      { id: "dbms-pyq-6", name: "DBMS - Indexing", count: 13 },
      { id: "dbms-pyq-7", name: "DBMS - Joins", count: 7 },
      { id: "dbms-pyq-8", name: "DBMS - Relational Algebra", count: 31 },
      { id: "dbms-pyq-9", name: "DBMS - Relational Calculus", count: 15 },
      { id: "dbms-pyq-10", name: "DBMS - SQL", count: 58 },
      { id: "dbms-pyq-11", name: "DBMS - Transaction and Concurrency", count: 30 },
    ],
  },
  {
    id: "cn",
    name: "Computer Networks",
    volume: "Volume 2",
    topics: [
      { id: "cn-pyq-1", name: "CN - Application Layer Protocols", count: 12 },
      { id: "cn-pyq-2", name: "CN - Congestion Control", count: 6 },
      { id: "cn-pyq-3", name: "CN - Error Detection", count: 10 },
      { id: "cn-pyq-4", name: "CN - IP Addressing", count: 11 },
      { id: "cn-pyq-5", name: "CN - IP Packet", count: 11 },
      { id: "cn-pyq-6", name: "CN - MAC Protocol", count: 5 },
      { id: "cn-pyq-7", name: "CN - Routing", count: 13 },
      { id: "cn-pyq-8", name: "CN - Sliding Window", count: 15 },
      { id: "cn-pyq-9", name: "CN - Stop and Wait", count: 6 },
      { id: "cn-pyq-10", name: "CN - Subnetting", count: 21 },
      { id: "cn-pyq-11", name: "CN - TCP", count: 22 },
      { id: "cn-pyq-12", name: "CN - UDP", count: 4 },
    ],
  },
  {
    id: "digital-logic",
    name: "Digital Logic",
    volume: "Volume 2",
    topics: [
      { id: "dl-pyq-1", name: "Digital Logic - Adder", count: 9 },
      { id: "dl-pyq-2", name: "Digital Logic - Boolean Algebra", count: 34 },
      { id: "dl-pyq-3", name: "Digital Logic - Circuit Output", count: 40 },
      { id: "dl-pyq-4", name: "Digital Logic - Digital Counter", count: 17 },
      { id: "dl-pyq-5", name: "Digital Logic - Flip Flop", count: 6 },
      { id: "dl-pyq-6", name: "Digital Logic - Floating Point Representation", count: 12 },
      { id: "dl-pyq-7", name: "Digital Logic - K Map", count: 20 },
      { id: "dl-pyq-8", name: "Digital Logic - Min Sum of Products", count: 15 },
      { id: "dl-pyq-9", name: "Digital Logic - Multiplexer", count: 14 },
      { id: "dl-pyq-10", name: "Digital Logic - Number Representation", count: 58 },
      { id: "dl-pyq-11", name: "Digital Logic - Sequential Circuit", count: 1 },
    ],
  },
  {
    id: "coa",
    name: "Computer Organization & Architecture",
    volume: "Volume 2",
    topics: [
      { id: "coa-pyq-1", name: "COA - Addressing Modes", count: 18 },
      { id: "coa-pyq-2", name: "COA - Cache Memory", count: 73 },
      { id: "coa-pyq-3", name: "COA - DMA", count: 9 },
      { id: "coa-pyq-4", name: "COA - Data Path", count: 7 },
      { id: "coa-pyq-5", name: "COA - Instruction Format", count: 9 },
      { id: "coa-pyq-6", name: "COA - Interrupts", count: 9 },
      { id: "coa-pyq-7", name: "COA - Machine Instruction", count: 21 },
      { id: "coa-pyq-8", name: "COA - Memory Interfacing", count: 6 },
      { id: "coa-pyq-9", name: "COA - Microprogramming", count: 13 },
      { id: "coa-pyq-10", name: "COA - Pipelining", count: 43 },
      { id: "coa-pyq-11", name: "COA - Runtime Environment", count: 2 },
      { id: "coa-pyq-12", name: "COA - Virtual Memory", count: 3 },
    ],
  },
  {
    id: "aptitude",
    name: "General Aptitude",
    volume: "Volume 1",
    topics: [
      { id: "apt-pyq-1", name: "Analytical Aptitude - Direction Sense", count: 12 },
      { id: "apt-pyq-2", name: "Analytical Aptitude - Logical Reasoning", count: 39 },
      { id: "apt-pyq-3", name: "Analytical Aptitude - Seating Arrangement", count: 4 },
      { id: "apt-pyq-4", name: "Analytical Aptitude - Sequence Series", count: 12 },
      { id: "apt-pyq-5", name: "Analytical Aptitude - Statements Follow", count: 33 },
      { id: "apt-pyq-6", name: "Quantitative Aptitude - Data Interpretation", count: 5 },
      { id: "apt-pyq-7", name: "Quantitative Aptitude - Geometry", count: 29 },
      { id: "apt-pyq-8", name: "Quantitative Aptitude - Logarithms", count: 14 },
      { id: "apt-pyq-9", name: "Quantitative Aptitude - Percentage", count: 21 },
      { id: "apt-pyq-10", name: "Quantitative Aptitude - Probability", count: 29 },
      { id: "apt-pyq-11", name: "Quantitative Aptitude - Ratio Proportion", count: 26 },
      { id: "apt-pyq-12", name: "Quantitative Aptitude - Speed Time Distance", count: 19 },
      { id: "apt-pyq-13", name: "Quantitative Aptitude - Venn Diagram", count: 16 },
      { id: "apt-pyq-14", name: "Spatial Aptitude - Image Rotation", count: 7 },
      { id: "apt-pyq-15", name: "Spatial Aptitude - Paper Folding", count: 12 },
      { id: "apt-pyq-16", name: "Verbal Aptitude - Most Appropriate Word", count: 113 },
      { id: "apt-pyq-17", name: "Verbal Aptitude - Passage Reading", count: 57 },
      { id: "apt-pyq-18", name: "Verbal Aptitude - Synonyms", count: 19 },
      { id: "apt-pyq-19", name: "Verbal Aptitude - Tenses", count: 25 },
      { id: "apt-pyq-20", name: "Verbal Aptitude - Word Pairs", count: 30 },
    ],
  },
];

export function getPyqSubjectById(subjectId: string): PyqSubject | undefined {
  return PYQ_SUBJECTS.find((subject) => subject.id === subjectId);
}
